
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnsxnoirjroduatqiaje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuc3hub2lyanJvZHVhdHFpYWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzg2OTEsImV4cCI6MjA2MTY1NDY5MX0.sld87NrGLsO_ID3JfsP4ldvy6SkNp3feu_nG6tVdhd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
